# Generated by Django 2.1.7 on 2019-04-19 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('summary', models.TextField(default='do some summary for today!')),
            ],
        ),
        migrations.CreateModel(
            name='DetailArrangement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('isfinished', models.BooleanField(verbose_name='detail arrangement state')),
                ('item_duration', models.CharField(choices=[('M', 'Morning things'), ('A', 'Afternoon things'), ('E', 'Evening Things')], max_length=1)),
                ('day_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DayCard')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_content', models.TextField(verbose_name='write some notes here')),
                ('day_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DayCard')),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_item_name', models.CharField(max_length=20)),
                ('isfinished', models.BooleanField(verbose_name='todo-item state')),
                ('day_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DayCard')),
            ],
        ),
    ]
