# Generated by Django 2.1.7 on 2019-04-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_daycard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailarrangement',
            name='time',
            field=models.DateTimeField(verbose_name='arranged-time'),
        ),
    ]
