# Generated by Django 2.1.7 on 2019-04-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190423_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailarrangement',
            name='isfinished',
            field=models.BooleanField(verbose_name='arrangement state'),
        ),
        migrations.AlterField(
            model_name='detailarrangement',
            name='time',
            field=models.CharField(max_length=5),
        ),
    ]
